modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Kore Team"
description = '''
${description}
'''
displayURL="${website}"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "pronouns.mixins.json"
